[book]
authors = ["Egemen Göl"]
language = "en"
multilingual = false
src = "src"
title = "zkPassport Docs"

[preprocessor.plantuml]
plantuml-cmd = "java -jar $(brew --prefix plantuml)/libexec/plantuml.jar"

[output.html]
default-theme = "navy"
